import os
os.listdir()

In [2]:
import pandas

In [4]:
df1=pandas.read_csv("supermarkets.csv")
df1.set_index("ID")

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [6]:
df2=pandas.read_json("supermarkets.json")
df2.set_index("ID")

Address           City Country  Employees         Name  \
ID                                                                   
1      3666 21st St  San Francisco     USA          8      Madeira   
2    735 Dolores St  San Francisco     USA         15  Bready Shop   
3       332 Hill St  San Francisco     USA         25  Super River   
4      3995 23rd St  San Francisco     USA         10   Ben's Shop   
5   1056 Sanchez St  San Francisco     USA         12      Sanchez   
6   551 Alvarado St  San Francisco     USA         20   Richvalley   

               State  
ID                    
1           CA 94114  
2           CA 94119  
3   California 94114  
4           CA 94114  
5         California  
6           CA 94114

In [9]:
df3=pandas.read_excel("supermarkets.xlsx", sheet_name=0)
df3

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [13]:
df4=pandas.read_csv("supermarkets-commas.txt")
df1.set_index("ID")

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [19]:
df5=pandas.read_csv("supermarkets-semi-colons.txt", sep=";")
df5.set_index("ID")

Address           City             State Country          Name  \
ID                                                                           
1      3666 21st St  San Francisco          CA 94114     USA       Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA   Super River   
4      3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA       Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [25]:
df6=pandas.read_csv("http://pythonhow.com/supermarkets.csv")
df6.set_index("Address")

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [36]:
df6.loc["735 Dolores St":"332 Hill St", "ID":"Country"]

ID           City             State Country
Address                                                    
735 Dolores St   2  San Francisco          CA 94119     USA
332 Hill St      3  San Francisco  California 94114     USA

In [38]:
df6

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [45]:
df6.iloc[3, 3]

'USA'

In [48]:
df6.ix[3,"Name"]

c:\users\suncan.stilinovic\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


"Ben's Shop"

In [54]:
df6

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [58]:
df6["Continent"] = df6.shape[0]*["North America"]

In [66]:
df6

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees          Continent  
Address                                        
3666 21st St             8  USA,North America  
735 Dolores St          15  USA,North America  
332 Hill St             25  USA,North America  
3995 23rd St            10  USA,North America  
1056 Sanchez St         12  USA,North America  
551 Alvarado St         20  USA,North America

In [67]:
df6_t=df6.T
df6_t

Address         3666 21st St     735 Dolores St        332 Hill St  \
ID                         1                  2                  3   
City           San Francisco      San Francisco      San Francisco   
State               CA 94114           CA 94119   California 94114   
Country                  USA                USA                USA   
Name                 Madeira        Bready Shop        Super River   
Employees                  8                 15                 25   
Continent  USA,North America  USA,North America  USA,North America   

Address         3995 23rd St    1056 Sanchez St    551 Alvarado St  
ID                         4                  5                  6  
City           San Francisco      San Francisco      San Francisco  
State               CA 94114         California           CA 94114  
Country                  USA                USA                USA  
Name              Ben's Shop            Sanchez         Richvalley  
Employees                 10                 12                 20  
Continent  USA,North America  USA,North America  USA,North America

In [68]:
df6_t["My Address"]=[7, "My City", "My State", "My Country", "My Name", 1000, "My Continent"]

In [70]:
df6=df6_t.T

df6 

In [71]:
df6

ID           City             State     Country         Name  \
Address                                                                        
3666 21st St     1  San Francisco          CA 94114         USA      Madeira   
735 Dolores St   2  San Francisco          CA 94119         USA  Bready Shop   
332 Hill St      3  San Francisco  California 94114         USA  Super River   
3995 23rd St     4  San Francisco          CA 94114         USA   Ben's Shop   
1056 Sanchez St  5  San Francisco        California         USA      Sanchez   
551 Alvarado St  6  San Francisco          CA 94114         USA   Richvalley   
My Address       7        My City          My State  My Country      My Name   

                Employees          Continent  
Address                                       
3666 21st St            8  USA,North America  
735 Dolores St         15  USA,North America  
332 Hill St            25  USA,North America  
3995 23rd St           10  USA,North America  
1056 Sanchez St        12  USA,North America  
551 Alvarado St        20  USA,North America  
My Address           1000       My Continent

In [72]:
import geopy

In [74]:
from geopy.geocoders import ArcGIS

In [75]:
nom = ArcGIS()

In [77]:
n = nom.geocode("3995 23rd St, San Francisco, CA 94114")

In [81]:
df = pandas.read_csv("supermarkets.csv")

In [82]:
df["Address"]=df["Address"]+", "+df["City"]+", "+df["State"]+", "+df["Country"]
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  
0          CA 94114     USA      Madeira          8  
1          CA 94119     USA  Bready Shop         15  
2  California 94114     USA  Super River         25  
3          CA 94114     USA   Ben's Shop         10  
4        California     USA      Sanchez         12  
5          CA 94114     USA   Richvalley         20

In [83]:
df["Coordinates"]=df["Address"].apply(nom.geocode)
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates  
0  (3666 21st St, San Francisco, California, 9411...  
1  (735 Dolores St, San Francisco, California, 94...  
2  (332 Hill St, San Francisco, California, 94114...  
3  (3995 23rd St, San Francisco, California, 9411...  
4  (1056 Sanchez St, San Francisco, California, 9...  
5  (551 Alvarado St, San Francisco, California, 9...

In [84]:
df["Latitude"]=df["Coordinates"].apply(lambda x: x.latitude)
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates   Latitude  
0  (3666 21st St, San Francisco, California, 9411...  37.756444  
1  (735 Dolores St, San Francisco, California, 94...  37.757801  
2  (332 Hill St, San Francisco, California, 94114...  37.755641  
3  (3995 23rd St, San Francisco, California, 9411...  37.752985  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752144  
5  (551 Alvarado St, San Francisco, California, 9...  37.753709

In [85]:
df["Longitude"]=df["Coordinates"].apply(lambda x: x.longitude)
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates   Latitude   Longitude  
0  (3666 21st St, San Francisco, California, 9411...  37.756444 -122.429353  
1  (735 Dolores St, San Francisco, California, 94...  37.757801 -122.425599  
2  (332 Hill St, San Francisco, California, 94114...  37.755641 -122.428794  
3  (3995 23rd St, San Francisco, California, 9411...  37.752985 -122.431702  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752144 -122.429758  
5  (551 Alvarado St, San Francisco, California, 9...  37.753709 -122.433251

In [86]:
import numpy

In [87]:
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [91]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [92]:
import cv2

In [104]:
im_g=cv2.imread("smallgray.png",0)

In [105]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [99]:
cv2.imwrite("newsmallgrey.png", im_g)

True

In [100]:
a=[1,2,3]

In [107]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [111]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [112]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [116]:
ims=numpy.hstack((im_g, im_g,im_g))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
        255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
         97, 182]], dtype=uint8)

In [118]:
lst=numpy.hsplit(ims,3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [119]:
vst=numpy.vsplit(ims, 3)
vst

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
         121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
         255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
          97, 182]], dtype=uint8)]